version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public

  php:
    build: ./docker/php/
    volumes:
      - ./:/app
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "lrqdo"
      MYSQL_ROOT_PASSWORD: "root"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    links:
      - db
    ports:
      - 8085:80
